targets = [
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-unknown-linux-gnu" },
]

[advisories]
yanked = "deny"
unsound = "deny"

[bans]
deny = [
    { name = "openssl-sys" },
]

[licenses]
allow = ["MIT", "BSD-3-Clause", "Apache-2.0", "ISC", "Unicode-DFS-2016"]
copyleft = "deny"
exceptions = [
    { name = "ring", allow = ["OpenSSL", "MIT", "ISC"] }
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]
